import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowUpLeft, Paintbrush, Layers3, MapPin } from "lucide-react";
import { ColorStudio } from "@/components/color-studio";
import { CatalogSection } from "@/components/catalog-section";
import { ContactBand } from "@/components/contact-band";
import { BusinessLocation } from "@/components/business-location";
import { ServiceCard } from "@/components/service-card";
import { services } from "@/data/services";
import { defaultWhatsAppMessage, whatsappUrl } from "@/data/site";
const faq = [{question:"كيف أختار المنتج المناسب؟",answer:"أرسل لنا نوع السطح ومكان الاستخدام، داخليًا أو خارجيًا، وصورة للمكان إن أمكن. نساعدك في تحديد منتج التأسيس أو الدهان أو الحماية المناسب."},{question:"كيف أعرف سعر المنتج وتوفره؟",answer:"تواصل معنا باسم المنتج عبر واتساب أو الاتصال. نؤكد لك السعر والتوفر والعبوات المتاحة قبل الطلب."},{question:"هل تقدمون خدمات تنفيذ في الرياض؟",answer:"نقدم خدمات تنفيذ الدهانات والتشطيبات في الرياض. يتم تحديد نطاق العمل والمواد والموعد بعد معرفة تفاصيل المشروع أو المعاينة."}];
export default function Home() {
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}).replace(/</g,"\\u003c")}}/>
  <section className="home-hero"><div className="container-shell hero-layout"><div className="hero-copy"><p className="hero-eyebrow"><span/> دهانات عليا · متجر دهانات بالرياض</p><h1>كل لون،<br/><span className="hero-title-accent">حكاية جديدة.<svg viewBox="0 0 390 18" fill="none" aria-hidden="true"><path d="M3 12C101 2 208 2 383 7M36 16C155 8 264 8 388 12" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg></span></h1><p className="hero-description">ألوان تمنح المكان روحه، ودهانات تكمل تفاصيله. اكتشف مجموعة عليا للدهانات الداخلية والخارجية وطلاءات الحماية.</p><div className="hero-actions"><Link href="/products" className="button button-primary">اكتشف المنتجات <ArrowLeft size={20}/></Link><a href={whatsappUrl(defaultWhatsAppMessage)} target="_blank" rel="noreferrer" className="button button-outline">نساعدك تختار <ArrowUpLeft size={19}/></a></div><div className="hero-palette"><div className="palette-dots" aria-hidden="true">{["#235d71","#db684e","#f2c978","#a4b7a0","#d9cabb"].map(color=><span key={color} style={{backgroundColor:color}}/>)}</div><a href="#color-studio">جرّب تناغم الألوان <ArrowUpLeft size={14}/></a></div></div><div className="hero-art"><span className="hero-colour-signature" aria-hidden="true"><i/><i/><i/></span><span className="hero-frame-line" aria-hidden="true"/><div className="hero-photo"><Image src="/hero-color-story.webp" alt="إلهام لوني لمساحة معاصرة بجدار أزرق وكرسي بلون مرجاني" fill priority sizes="(max-width: 800px) 100vw, 52vw" className="object-cover"/><span className="hero-photo-caption" dir="ltr">THE ART OF COLOUR</span></div><div className="hero-color-card"><span className="color-chip"/><div><small>إلهام لمساحتك</small><strong>تناغم يبدأ بلون</strong></div><ArrowUpLeft size={23}/></div><span className="hero-art-label" dir="ltr">ALYA PAINTS — COLOUR YOUR SPACE</span></div></div></section>
  <div className="benefit-strip"><div className="container-shell">{[{icon:Paintbrush,title:"دهانات داخلية وخارجية",text:"للجدران والأسقف والواجهات"},{icon:Layers3,title:"من التأسيس إلى الحماية",text:"اختيارات لكل مرحلة"},{icon:MapPin,title:"معك في الرياض",text:"منتجات وخدمات تنفيذ"}].map(({icon:Icon,title,text})=><div key={title}><Icon size={27} strokeWidth={1.4}/><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></div>
  <CatalogSection/>
  <ColorStudio/>
  <section className="section-space"><div className="container-shell"><div className="section-heading"><div><span className="eyebrow">نكمل معك التفاصيل</span><h2 className="section-title">من اختيار اللون،<br/>إلى جمال التنفيذ.</h2></div><div><p>خدمات دهانات وتشطيبات وديكورات في الرياض،<br/>تبدأ بفهم المكان والنتيجة التي تتطلع لها.</p><Link href="/services" className="text-link">اكتشف خدماتنا <ArrowLeft size={18}/></Link></div></div><div className="services-grid">{services.slice(0,3).map((service,index)=><ServiceCard key={service.slug} service={service} index={index}/>)}</div></div></section>
  <section className="faq-section section-space"><div className="container-shell faq-layout"><div><span className="eyebrow">قبل أن تبدأ</span><h2 className="section-title">اختيار أوضح.<br/>نتيجة أجمل.</h2></div><div className="faq-list">{faq.map((item,index)=><details key={item.question}><summary><span className="faq-number">0{index+1}</span>{item.question}<span className="faq-plus">+</span></summary><p>{item.answer}</p></details>)}</div></div></section>
  <BusinessLocation/><ContactBand/></main>;
}
