import type { AdsRow,GbpRow } from "./types";
export function riyadhDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
export function shiftDate(date:string,days:number){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
export function previousPeriod(from:string,to:string){const days=Math.round((Date.parse(to)-Date.parse(from))/86400000)+1;return{from:shiftDate(from,-days),to:shiftDate(from,-1),days};}
export function adsSummary(rows:AdsRow[],from:string,to:string){const selected=rows.filter(r=>r.date>=from&&r.date<=to);if(!selected.length)return null;const sums=selected.reduce((t,r)=>({spend:t.spend+r.spend,clicks:t.clicks+r.clicks,impressions:t.impressions+r.impressions,conversions:t.conversions+r.conversions}),{spend:0,clicks:0,impressions:0,conversions:0});return{...sums,ctr:sums.impressions?sums.clicks/sums.impressions*100:null,cpc:sums.clicks?sums.spend/sums.clicks:null,cpa:sums.conversions?sums.spend/sums.conversions:null,days:new Set(selected.map(r=>r.date)).size};}
export function gbpSummary(rows:GbpRow[],from:string,to:string){const selected=rows.filter(r=>r.date>=from&&r.date<=to);if(!selected.length)return null;return{...selected.reduce((t,r)=>({views:t.views+r.views,calls:t.calls+r.calls,websiteClicks:t.websiteClicks+r.websiteClicks,directions:t.directions+r.directions}),{views:0,calls:0,websiteClicks:0,directions:0}),days:new Set(selected.map(r=>r.date)).size};}
export function changeRate(current:number|undefined|null,previous:number|undefined|null){if(current===undefined||current===null||previous===undefined||previous===null||previous===0)return null;return(current-previous)/previous*100;}
export const numberFormat=(v:number|null|undefined,digits=0)=>v===null||v===undefined?"—":new Intl.NumberFormat("ar-SA",{maximumFractionDigits:digits}).format(v);
export const moneyFormat=(v:number|null|undefined)=>v===null||v===undefined?"—":new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2}).format(v);
