import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft, ArrowUpLeft, Check } from "lucide-react";
import { ServiceCard } from "@/components/service-card";
import { ContactBand } from "@/components/contact-band";
import { services, getService } from "@/data/services";
import { site, whatsappUrl } from "@/data/site";
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return services.map(service=>({slug:service.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const s=getService(slug);if(!s)return{};return{title:s.title,description:s.summary,alternates:{canonical:`/services/${slug}`},openGraph:{title:s.title,description:s.summary,url:`/services/${slug}`,images:[{url:s.image,alt:s.shortTitle}]}};}
export default async function ServicePage({params}:Props){const {slug}=await params;const s=getService(slug);if(!s)notFound();const schema={"@context":"https://schema.org","@graph":[{"@type":"Service",name:s.shortTitle,description:s.description,url:`${site.url}/services/${slug}`,areaServed:{"@type":"City",name:site.city},provider:{"@id":`${site.url}/#business`}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"الرئيسية",item:site.url},{"@type":"ListItem",position:2,name:"الخدمات",item:`${site.url}/services`},{"@type":"ListItem",position:3,name:s.shortTitle,item:`${site.url}/services/${slug}`}]}]};return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><section className="service-detail-hero"><div className="container-shell"><nav className="breadcrumbs" aria-label="مسار التنقل"><Link href="/">الرئيسية</Link><ChevronLeft size={14}/><Link href="/services">الخدمات</Link><ChevronLeft size={14}/><span>{s.shortTitle}</span></nav><div className="service-detail-layout"><div><span className="eyebrow">{s.eyebrow}</span><h1>{s.title}</h1><p>{s.description}</p><a href={whatsappUrl(`السلام عليكم، أرغب في الاستفسار عن خدمة ${s.shortTitle} في الرياض.`)} target="_blank" rel="noreferrer" className="button button-primary">ناقش مشروعك معنا <ArrowUpLeft size={19}/></a></div><div className="service-detail-image"><Image src={s.image} alt={s.shortTitle} fill priority sizes="(max-width:680px) 100vw, 50vw" className="object-cover"/></div></div></div></section><section className="section-space bg-secondary"><div className="container-shell service-info-grid"><div><span className="eyebrow">عناية بالتفاصيل</span><h2>ما يميز الخدمة</h2><ul>{s.benefits.map(text=><li key={text}><Check size={18}/>{text}</li>)}</ul></div><div><span className="eyebrow">خطوات واضحة</span><h2>يشمل نطاق العمل</h2><ul>{s.includes.map(text=><li key={text}><Check size={18}/>{text}</li>)}</ul></div></div></section><section className="section-space"><div className="container-shell"><div className="section-heading"><h2 className="section-title">خدمات تكمل مشروعك.</h2></div><div className="services-grid">{services.filter(item=>item.slug!==slug).slice(0,3).map(item=><ServiceCard key={item.slug} service={item}/>)}</div></div></section><ContactBand/></main>;}
