import type { Metadata } from "next";
import type { CSSProperties } from "react";
import Link from "next/link";
import { notFound, permanentRedirect } from "next/navigation";
import { ChevronLeft, ArrowUpLeft } from "lucide-react";
import { ProductPackshot } from "@/components/product-packshot";
import { ProductBackdrop } from "@/components/product-backdrop";
import { ProductCard } from "@/components/catalog-products";
import { publicProducts, publicProduct } from "@/lib/admin/catalog";
import { site, whatsappUrl } from "@/data/site";
type Props={params:Promise<{slug:string}>};
export const dynamicParams=true;
export const revalidate=60;
export async function generateStaticParams(){return [...(await publicProducts()).map(p=>({slug:p.slug})),{slug:"alya-paints"},{slug:"alya-thermal"}];}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=await publicProduct(slug);if(!p)return{};return{title:`${p.title} | ${p.name}`,description:p.description,alternates:{canonical:`/products/${slug}`},openGraph:{title:p.title,description:p.description,url:`/products/${slug}`,images:[{url:p.image,alt:p.title}]}};}
export default async function ProductPage({params}:Props){
 const {slug}=await params;if(slug==="alya-paints")permanentRedirect("/products#paints");if(slug==="alya-thermal")permanentRedirect("/products#thermal");const p=await publicProduct(slug);if(!p)notFound();const products=await publicProducts(); const related=products.filter(item=>item.collection===p.collection&&item.slug!==slug).slice(0,4);
 const theme={tone:p.tone,accent:p.accent};
 const schema={"@context":"https://schema.org","@graph":[{"@type":"Product","@id":`${site.url}/products/${slug}#product`,name:p.title,alternateName:p.name,description:p.description,image:new URL(p.image,site.url).toString(),url:`${site.url}/products/${slug}`,category:p.category,brand:{"@type":"Brand",name:"Alya Paints"},...(p.price!=null?{offers:{"@type":"Offer",url:`${site.url}/products/${slug}`,price:p.price,priceCurrency:"SAR",seller:{"@id":`${site.url}/#business`},...(p.availability!=="unspecified"?{availability:`https://schema.org/${p.availability==="in-stock"?"InStock":p.availability==="out-of-stock"?"OutOfStock":"PreOrder"}`}:{})}}:{})},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"الرئيسية",item:site.url},{"@type":"ListItem",position:2,name:"المنتجات",item:`${site.url}/products`},{"@type":"ListItem",position:3,name:p.title,item:`${site.url}/products/${slug}`}]}]};
 return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><section className="product-detail"><div className="container-shell"><nav className="breadcrumbs" aria-label="مسار التنقل"><Link href="/">الرئيسية</Link><ChevronLeft size={14}/><Link href="/products">المنتجات</Link><ChevronLeft size={14}/><span>{p.title}</span></nav><div className="product-detail-grid"><div className="product-detail-art" style={{backgroundColor:theme.tone,"--stage-accent":theme.accent} as CSSProperties}><span className="stage-label" dir="ltr">ALYA PAINTS / PRODUCT</span><ProductBackdrop/><ProductPackshot product={p} suffix="detail"/><span className="stage-name" dir="ltr">{p.name}</span></div><div className="product-detail-copy"><span className="eyebrow">{p.category}</span><span className="product-english" dir="ltr">{p.name}</span><h1>{p.title}</h1><p className="product-detail-use">{p.use}</p><p className="product-detail-description">{p.description}</p>{p.price!=null&&<p className="public-product-price detail-price">{new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"}).format(p.price)}</p>}{p.availability!=="unspecified"&&<p className="product-availability">{p.availability==="in-stock"?"متوفر":p.availability==="out-of-stock"?"غير متوفر حاليًا":"متاح للطلب المسبق"}</p>}<dl className="product-meta"><div><dt>المجموعة</dt><dd dir="ltr">{p.collection}</dd></div><div><dt>الاستخدام</dt><dd>{p.use}</dd></div></dl><a href={whatsappUrl(`السلام عليكم، أرغب في الاستفسار عن ${p.title} (${p.name}) وسعره وتوفره والعبوات المتاحة وطريقة الاستخدام.`)} target="_blank" rel="noreferrer" className="button button-primary">اسأل عن المنتج <ArrowUpLeft size={20}/></a><p className="product-note">تواصل معنا لتأكيد السعر والتوفر والعبوات المناسبة لمشروعك.</p></div></div></div></section><section className="section-space detail-related"><div className="container-shell"><div className="section-heading"><div><span className="eyebrow">اكتشف المزيد</span><h2 className="section-title">من المجموعة نفسها.</h2></div><Link href="/products" className="text-link">كل المنتجات <ArrowUpLeft size={18}/></Link></div><div className="product-grid">{related.map(item=><ProductCard key={item.slug} product={item} index={products.indexOf(item)}/>)}</div></div></section></main>;
}
