"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowUpLeft,Eye,EyeOff,LockKeyhole,LoaderCircle,ShieldCheck,UserRound } from "lucide-react";
import { BrandSymbol } from "@/components/brand-mark";
export function AdminLogin(){const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[show,setShow]=useState(false);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setError("");setBusy(true);const form=new FormData(event.currentTarget);try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:form.get("username"),password:form.get("password")})});const data=await r.json();if(!r.ok)throw new Error(data.error);window.location.assign("/dashboard");}catch(e){setError(e instanceof Error?e.message:"تعذّر تسجيل الدخول.");setBusy(false);}}
 return <main className="alya-login"><div className="login-story"><Link href="/" className="login-brand"><span><BrandSymbol/></span><div><strong>دهانات عليا</strong><small dir="ltr">ALYA PAINTS / CONTROL CENTER</small></div></Link><div className="login-story-copy"><span className="admin-kicker">مساحة الإدارة</span><h1>كل تفاصيل عليا،<br/><em>في مساحة واحدة.</em></h1><p>منتجاتك، حضورك، ونتائجك.<br/>إدارة أوضح تترك لك مساحة للإبداع.</p></div><div className="login-art" aria-hidden="true"><div className="paint-arch"/><BrandSymbol/><i/><i/><i/></div><span className="login-story-footer">ألوان تكمّل المكان. أدوات تكمّل العمل.</span></div><div className="login-panel"><Link href="/" className="login-back">زيارة الموقع <ArrowUpLeft size={17}/></Link><div className="login-card"><div className="login-avatar"><BrandSymbol/></div><span className="admin-kicker">أهلًا بك في عليا</span><h2>لنبدأ يومًا مثمرًا.</h2><p>سجّل دخولك لإدارة المنتجات ومتابعة التقارير.</p><form onSubmit={submit}><label htmlFor="admin-user">اسم المستخدم</label><div className="admin-input-icon"><UserRound size={18}/><input id="admin-user" name="username" autoComplete="username" dir="ltr" required placeholder="اسم المستخدم" maxLength={50}/></div><label htmlFor="admin-password">كلمة المرور</label><div className="admin-input-icon"><LockKeyhole size={18}/><input id="admin-password" name="password" autoComplete="current-password" dir="ltr" type={show?"text":"password"} required maxLength={200} placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"إخفاء كلمة المرور":"إظهار كلمة المرور"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<p role="alert" className="admin-error">{error}</p>}<button className="admin-button admin-primary login-submit" disabled={busy}>{busy?<LoaderCircle className="admin-spin" size={19}/>:<>دخول لوحة التحكم <ArrowUpLeft size={19}/></>}</button></form><span className="login-security"><ShieldCheck size={16}/>دخول خاص بإدارة دهانات عليا</span></div><span className="login-panel-footer">دهانات عليا · الرياض</span></div></main>;
}
