"use client";
import { useEffect,useRef,useState } from "react";
import {FileSpreadsheet,LoaderCircle,Upload,X,Download} from "lucide-react";
import {parseCsv} from "@/lib/admin/csv";
const fields={ads:[["date","التاريخ"],["campaign","اسم الحملة"],["campaignId","معرّف الحملة"],["impressions","مرات الظهور"],["clicks","النقرات"],["spend","الإنفاق"],["conversions","التحويلات"]],gbp:[["date","التاريخ"],["views","مشاهدات الملف"],["calls","ضغطات الاتصال"],["websiteClicks","نقرات الموقع"],["directions","طلبات الاتجاهات"]]};
const aliases:Record<string,string[]>={date:["date","day","التاريخ","اليوم"],campaign:["campaign","الحملة","اسم الحملة"],campaignId:["campaignid","campaign_id","campaign id","معرّف الحملة","معرف الحملة","رقم تعريف الحملة"],impressions:["impressions","impr.","مرات الظهور","ظهور"],clicks:["clicks","النقرات","نقرات"],spend:["spend","cost","التكلفة","الإنفاق"],conversions:["conversions","conv.","التحويلات","الإحالات الناجحة"],views:["views","impressions","مشاهدات الملف","عدد المشاهدات","المشاهدات"],calls:["calls","call_clicks","ضغطات الاتصال","الاتصالات","المكالمات"],websiteClicks:["websiteclicks","website_clicks","نقرات الموقع","نقرات الموقع الإلكتروني"],directions:["directions","direction_requests","طلبات الاتجاهات","طلبات الحصول على الاتجاهات"]};
export function ReportImport({kind,identity,onClose,onSave}:{kind:"ads"|"gbp";identity:string;onClose:()=>void;onSave:(csv:string,identity:string)=>Promise<void>}){
 const modal=useRef<HTMLDialogElement>(null);const[rows,setRows]=useState<Record<string,string>[]>([]);const[map,setMap]=useState<Record<string,string>>({});const[account,setAccount]=useState(identity);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[confirmed,setConfirmed]=useState(false);const[name,setName]=useState("");
 useEffect(()=>{const dialog=modal.current;dialog?.showModal();return()=>dialog?.close();},[]);
 async function fileSelected(file:File|undefined){if(!file)return;setError("");try{const bytes=await file.arrayBuffer();if(bytes.byteLength>750000)throw new Error("اختر ملفًا حتى ٧٥٠ كيلوبايت.");const arr=new Uint8Array(bytes);const encoding=arr[0]===255&&arr[1]===254?"utf-16le":"utf-8";const parsed=parseCsv(new TextDecoder(encoding).decode(bytes));if(parsed.length>15000)throw new Error("الحد الأقصى ١٥٠٠٠ صف.");const headers=Object.keys(parsed[0]);setMap(Object.fromEntries(fields[kind].map(([key])=>[key,headers.find(h=>aliases[key].includes(h.trim().toLowerCase()))||""])));setRows(parsed);setName(file.name);}catch(e){setError(e instanceof Error?e.message:"تنسيق غير صالح.");}}
 function downloadTemplate(){const headers=fields[kind].map(([key])=>key);if(kind==="ads")headers.push("currency");const url=URL.createObjectURL(new Blob([headers.join(",")+"\r\n"],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`alya-${kind}-template.csv`;a.click();URL.revokeObjectURL(url);}
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);try{if(!rows.length||fields[kind].some(([key])=>!map[key]))throw new Error("اختر العمود المقابل لكل مؤشر.");const converted=rows.map(r=>({...Object.fromEntries(fields[kind].map(([key])=>[key,r[map[key]]])),...(kind==="ads"?{currency:r.currency||r.Currency||"SAR"}:{})}));const headers=Object.keys(converted[0]);const quote=(v:unknown)=>'"'+String(v??"").replace(/"/g,'""')+'"';const csv=[headers.map(quote).join(","),...converted.map(r=>headers.map(k=>quote((r as Record<string,unknown>)[k])).join(","))].join("\n");await onSave(csv,account);}catch(e){setError(e instanceof Error?e.message:"تعذّر الاستيراد.");setBusy(false);}}
 return <dialog ref={modal} className="admin-modal import-modal" onCancel={onClose}><form onSubmit={submit}><header className="modal-heading"><div><span className="admin-kicker">بيانات موثوقة. قراءة أوضح.</span><h2>استيراد تقرير {kind==="ads"?"Google Ads":"الملف التجاري"}</h2></div><button type="button" className="admin-icon-button" onClick={onClose} aria-label="إغلاق الاستيراد"><X size={22}/></button></header><div className="import-body"><div className="import-guidance"><FileSpreadsheet size={27}/><p>{kind==="ads"?"استخدم تقرير الحملات مقسمًا حسب اليوم، لحساب واحد وبعملة SAR.":"استخدم تقرير الأداء اليومي لملف دهانات عليا فقط."}<small>الاستيراد يحدّث الصفوف المطابقة ويحافظ على الأيام السابقة دون مضاعفة النتائج.</small></p><button type="button" onClick={downloadTemplate} className="admin-button admin-secondary"><Download size={15}/>نموذج التنسيق</button></div><label className="admin-upload import-file"><Upload size={22}/>{name||"اختر ملف CSV أو TSV"}<input type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" onChange={e=>fileSelected(e.target.files?.[0])}/></label><label className="admin-field">{kind==="ads"?"معرّف حساب Google Ads":"معرّف الملف التجاري"}<input value={account} onChange={e=>setAccount(e.target.value)} required dir="ltr" maxLength={100} placeholder={kind==="ads"?"1234567890":"locations/123456789"}/></label>{rows.length>0&&<><p className="admin-help">تمت قراءة {rows.length} صف. طابق أعمدة الملف بالمؤشرات:</p><div className="import-mapping">{fields[kind].map(([key,label])=><label key={key}>{label}<select value={map[key]||""} required onChange={e=>setMap(m=>({...m,[key]:e.target.value}))}><option value="">اختر عمودًا</option>{Object.keys(rows[0]).map(h=><option key={h}>{h}</option>)}</select></label>)}</div><div className="import-preview"><strong>معاينة أول صف</strong><dl>{fields[kind].slice(0,4).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{rows[0][map[key]]||"—"}</dd></div>)}</dl></div></>}<label className="admin-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} required/><span>التقرير يخص دهانات عليا{kind==="ads"?"، بعملة الريال السعودي":"، وضغطات الاتصال ليست مكالمات مكتملة"}.</span></label>{error&&<p className="admin-error" role="alert">{error}</p>}</div><footer className="modal-footer"><span>لا تُعرض أرقام دون بيانات مصدر.</span><div><button type="button" className="admin-button admin-secondary" onClick={onClose} disabled={busy}>إلغاء</button><button className="admin-button admin-primary" disabled={busy||!rows.length||!confirmed}>{busy?<LoaderCircle className="admin-spin" size={18}/>:<>استيراد التقرير <Upload size={17}/></>}</button></div></footer></form></dialog>;
}
