import type { Metadata } from "next";
import Link from "next/link";
import { notFound, permanentRedirect } from "next/navigation";
import { ChevronLeft, ArrowUpLeft } from "lucide-react";
import { ProductPackshot } from "@/components/product-packshot";
import { ProductCard } from "@/components/catalog-products";
import { products, getProduct, productTones } from "@/data/products";
import { site, whatsappUrl } from "@/data/site";
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return [...products.map(p=>({slug:p.slug})),{slug:"alya-paints"},{slug:"alya-thermal"}];}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=getProduct(slug);if(!p)return{};return{title:`${p.title} | ${p.name}`,description:`${p.title}: ${p.use}. تعرف على المنتج وتواصل مع متجر دهانات عليا في الرياض للاستفسار عن السعر والتوفر.`,alternates:{canonical:`/products/${slug}`},openGraph:{title:p.title,description:p.use,url:`/products/${slug}`,images:[{url:p.image,alt:p.title}]}};}
export default async function ProductPage({params}:Props){
 const {slug}=await params;if(slug==="alya-paints")permanentRedirect("/products#paints");if(slug==="alya-thermal")permanentRedirect("/products#thermal");const p=getProduct(slug);if(!p)notFound();const related=products.filter(item=>item.collection===p.collection&&item.slug!==slug).slice(0,4);
 const schema={"@context":"https://schema.org","@graph":[{"@type":"Product","@id":`${site.url}/products/${slug}#product`,name:p.title,alternateName:p.name,description:p.use,image:`${site.url}${p.image}`,url:`${site.url}/products/${slug}`,category:p.category,brand:{"@type":"Brand",name:"Alya Paints"}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"الرئيسية",item:site.url},{"@type":"ListItem",position:2,name:"المنتجات",item:`${site.url}/products`},{"@type":"ListItem",position:3,name:p.title,item:`${site.url}/products/${slug}`}]}]};
 return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/><section className="product-detail"><div className="container-shell"><nav className="breadcrumbs" aria-label="مسار التنقل"><Link href="/">الرئيسية</Link><ChevronLeft size={14}/><Link href="/products">المنتجات</Link><ChevronLeft size={14}/><span>{p.title}</span></nav><div className="product-detail-grid"><div className="product-detail-art" style={{backgroundColor:productTones[products.indexOf(p)%productTones.length]}}><span className="stage-label" dir="ltr">ALYA PAINTS / PRODUCT</span><div className="stage-disc" aria-hidden="true"/><ProductPackshot product={p} suffix="detail"/><span className="stage-name" dir="ltr">{p.name}</span></div><div className="product-detail-copy"><span className="eyebrow">{p.category}</span><span className="product-english" dir="ltr">{p.name}</span><h1>{p.title}</h1><p>{p.use}.</p><dl className="product-meta"><div><dt>المجموعة</dt><dd dir="ltr">{p.collection}</dd></div><div><dt>الاستخدام</dt><dd>{p.use}</dd></div></dl><a href={whatsappUrl(`السلام عليكم، أرغب في الاستفسار عن ${p.title} (${p.name}) وسعره وتوفره والعبوات المتاحة وطريقة الاستخدام.`)} target="_blank" rel="noreferrer" className="button button-primary">اسأل عن المنتج <ArrowUpLeft size={20}/></a><p className="product-note">تواصل معنا لتأكيد السعر والتوفر والعبوات المناسبة لمشروعك.</p></div></div></div></section><section className="section-space detail-related"><div className="container-shell"><div className="section-heading"><div><span className="eyebrow">اكتشف المزيد</span><h2 className="section-title">من المجموعة نفسها.</h2></div><Link href="/products" className="text-link">كل المنتجات <ArrowUpLeft size={18}/></Link></div><div className="product-grid">{related.map(item=><ProductCard key={item.slug} product={item} index={products.indexOf(item)}/>)}</div></div></section></main>;
}
